pipeline {

```
agent any

environment {
    IMAGE_TAG = "${BUILD_NUMBER}"
}

stages {

    stage('Checkout') {
        steps {
            git(
                credentialsId: 'github-credentials',
                url: 'https://github.com/DineshReddy6303/Jenkins-end-to-end.git',
                branch: 'main'
            )
        }
    }

    stage('Build Docker') {
        steps {
            sh '''
                echo "Build Docker Image"
                docker build -t DineshReddy6303/cicd-e2e:${BUILD_NUMBER} .
            '''
        }
    }

    stage('Push the artifacts') {
        steps {
            withCredentials([
                usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USERNAME',
                    passwordVariable: 'DOCKER_PASSWORD'
                )
            ]) {
                sh '''
                    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                    docker push DineshReddy6303/cicd-e2e:${BUILD_NUMBER}
                    docker logout
                '''
            }
        }
    }

    stage('Checkout K8S manifest SCM') {
        steps {
            git(
                credentialsId: 'github-credentials',
                url: 'https://github.com/DineshReddy6303/cicd-demo-manifests-repo.git',
                branch: 'main'
            )
        }
    }

    stage('Update K8S manifest & push to Repo') {
        steps {
            withCredentials([
                usernamePassword(
                    credentialsId: 'github-credentials',
                    usernameVariable: 'GIT_USERNAME',
                    passwordVariable: 'GIT_PASSWORD'
                )
            ]) {
                sh '''
                    echo "Before update:"
                    cat deploy.yaml

                    sed -i "s/32/${BUILD_NUMBER}/g" deploy.yaml

                    echo "After update:"
                    cat deploy.yaml

                    git config user.name "$GIT_USERNAME"
                    git config user.email "$GIT_USERNAME@users.noreply.github.com"

                    git add deploy.yaml
                    git commit -m "Updated deploy.yaml | Jenkins Pipeline" || echo "No changes to commit"

                    git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/DineshReddy6303/cicd-demo-manifests-repo.git HEAD:main
                '''
            }
        }
    }
}
```

}
