pipeline {
    agent any

    environment {
        IMAGE_NAME = "jibbbax/cicd-e2e"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Application') {
            steps {
                dir('application') {
                    git(
                        credentialsId: 'github-credentials',
                        url: 'https://github.com/DineshReddy6303/Jenkins-end-to-end.git',
                        branch: 'main'
                    )
                }
            }
        }

        stage('Build Docker') {
            steps {
                sh '''
                    echo "Building Docker Image"

                    cd application/python-jenkins-argocd-k8s

                    docker build \
                        -t ${IMAGE_NAME}:${IMAGE_TAG} .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'Dockerhub_Credentails',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login \
                            -u "$DOCKER_USERNAME" \
                            --password-stdin

                        docker push ${IMAGE_NAME}:${IMAGE_TAG}

                        docker logout
                    '''
                }
            }
        }

        stage('Checkout K8S Manifest') {
            steps {
                dir('k8s-manifests') {
                    git(
                        credentialsId: 'github-credentials',
                        url: 'https://github.com/DineshReddy6303/cicd-demo-manifests-repo.git',
                        branch: 'main'
                    )
                }
            }
        }

        stage('Update K8S Manifest') {
            steps {
                dir('k8s-manifests') {
                    sh '''
                        echo "Current directory:"
                        pwd

                        echo "Files:"
                        ls -la

                        echo "Before update:"
                        cat deploy.yaml

                        sed -i "s#jibbbax/cicd-e2e:[0-9]*#jibbbax/cicd-e2e:${BUILD_NUMBER}#g" deploy.yaml

                        echo "After update:"
                        cat deploy.yaml
                    '''
                }
            }
        }

        stage('Commit and Push K8S Manifest') {
            steps {
                dir('k8s-manifests') {
                    sh '''
                        git config user.name "Jenkins"
                        git config user.email "jenkins@localhost"

                        git add deploy.yaml

                        git commit -m "Update Docker image tag to ${BUILD_NUMBER}" || true

                        git push origin HEAD:main
                    '''
                }
            }
        }
    }
}
