pipeline {
  agent none
  stages {
    stage('Build') {
      agent {
        docker { image ''maven:3.8.8-eclipse-temurin-17' }
      }
      steps {
        sh 'mvn clean package'
      }
    }
    stage('Test') {
      agent {
        docker { image 'maven:3.8.8-eclipse-temurin-17' }
      }
      steps {
        sh 'mvn --test'
      }
    }
      stage('Docker) {
            agent {
              docker {
                image 'docker:24'
  }
}
            steps {
              sh 'docker --version'
            }
            }
            }
            }
